gui:
  sidePanelWidth: 0.3
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#585b70"
    searchingActiveBorderColor:
      - "#f9e2af"
      - bold
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#45475a"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
